"use client";
import React from "react";
import { Card, Row, Col, Button, Select, DatePicker, Table, Tag } from "antd";
import {
  FileTextOutlined,
  DownloadOutlined,
  TeamOutlined,
  CalendarOutlined,
  DashboardOutlined,
} from "@/components/icons/Icons";

const { RangePicker } = DatePicker;

const Reports: React.FC = () => {
  const reportTypes = [
    {
      title: "Attendance Report",
      description: "Daily, weekly, and monthly attendance summaries",
      icon: <CalendarOutlined className="text-3xl text-blue-600" />,
      bgColor: "bg-blue-50",
    },
    {
      title: "Employee Report",
      description: "Complete employee data and performance metrics",
      icon: <TeamOutlined className="text-3xl text-purple-600" />,
      bgColor: "bg-purple-50",
    },
    {
      title: "Recruitment Report",
      description: "Hiring pipeline, ATS metrics, and candidate analysis",
      icon: <FileTextOutlined className="text-3xl text-green-600" />,
      bgColor: "bg-green-50",
    },
    {
      title: "Payroll Report",
      description: "Salary disbursement, deductions, and tax reports",
      icon: <DashboardOutlined className="text-3xl text-orange-600" />,
      bgColor: "bg-orange-50",
    },
  ];

  const recentReportsColumns = [
    {
      title: "Report Name",
      dataIndex: "name",
      key: "name",
      render: (text: string) => (
        <span className="font-semibold text-gray-800">{text}</span>
      ),
    },
    {
      title: "Type",
      dataIndex: "type",
      key: "type",
      render: (type: string) => <Tag color="blue">{type}</Tag>,
    },
    {
      title: "Generated By",
      dataIndex: "generatedBy",
      key: "generatedBy",
    },
    {
      title: "Date",
      dataIndex: "date",
      key: "date",
      render: (date: string) => (
        <span className="text-gray-600">{date}</span>
      ),
    },
    {
      title: "Status",
      dataIndex: "status",
      key: "status",
      render: (status: string) => (
        <Tag color={status === "Completed" ? "green" : "orange"}>
          {status}
        </Tag>
      ),
    },
    {
      title: "Action",
      key: "action",
      render: () => (
        <Button
          type="link"
          icon={<DownloadOutlined />}
          className="text-blue-600"
        >
          Download
        </Button>
      ),
    },
  ];

  const recentReportsData = [
    {
      key: "1",
      name: "Monthly Attendance Report",
      type: "Attendance",
      generatedBy: "System",
      date: "Jan 20, 2026",
      status: "Completed",
    },
    {
      key: "2",
      name: "Employee Performance Q4",
      type: "Performance",
      generatedBy: "HR Manager",
      date: "Jan 18, 2026",
      status: "Completed",
    },
    {
      key: "3",
      name: "Recruitment Pipeline",
      type: "Recruitment",
      generatedBy: "System",
      date: "Jan 15, 2026",
      status: "Completed",
    },
  ];

  return (
    <div className="space-y-6">
      {/* Header */}
      <div>
        <h1 className="text-3xl font-bold text-gray-800">Reports & Analytics</h1>
        <p className="text-gray-600 mt-1">
          Generate and download comprehensive HR reports
        </p>
      </div>

      {/* Generate Report Section */}
      <Card
        title={<span className="text-lg font-semibold">Generate New Report</span>}
        className="bg-linear-to-r from-blue-50 to-purple-50"
      >
        <div className="space-y-4">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Report Type
              </label>
              <Select
                size="large"
                placeholder="Select report type"
                className="w-full"
                options={[
                  { value: "attendance", label: "Attendance Report" },
                  { value: "employee", label: "Employee Report" },
                  { value: "recruitment", label: "Recruitment Report" },
                  { value: "payroll", label: "Payroll Report" },
                  { value: "performance", label: "Performance Report" },
                ]}
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Date Range
              </label>
              <RangePicker size="large" className="w-full" />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Format
              </label>
              <Select
                size="large"
                defaultValue="pdf"
                className="w-full"
                options={[
                  { value: "pdf", label: "PDF" },
                  { value: "excel", label: "Excel" },
                  { value: "csv", label: "CSV" },
                ]}
              />
            </div>
          </div>
          <Button
            type="primary"
            icon={<FileTextOutlined />}
            size="large"
            className="bg-blue-600 hover:bg-blue-700"
          >
            Generate Report
          </Button>
        </div>
      </Card>

      {/* Report Types */}
      <div>
        <h2 className="text-xl font-bold text-gray-800 mb-4">Report Types</h2>
        <Row gutter={[16, 16]}>
          {reportTypes.map((report, index) => (
            <Col xs={24} sm={12} lg={6} key={index}>
              <Card
                className="hover:shadow-lg transition-all duration-300 hover:-translate-y-1 cursor-pointer"
                bodyStyle={{ padding: "24px" }}
              >
                <div className={`${report.bgColor} p-4 rounded-lg mb-4 w-fit`}>
                  {report.icon}
                </div>
                <h3 className="font-bold text-gray-800 mb-2">{report.title}</h3>
                <p className="text-sm text-gray-600">{report.description}</p>
              </Card>
            </Col>
          ))}
        </Row>
      </div>

      {/* Recent Reports */}
      <Card
        title={<span className="text-lg font-semibold">Recent Reports</span>}
      >
        <Table
          columns={recentReportsColumns}
          dataSource={recentReportsData}
          pagination={false}
          scroll={{ x: 800 }}
        />
      </Card>
    </div>
  );
};

export default Reports;
